[33m293d49a[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mdev[m[33m, [m[1;31morigin/dev[m[33m)[m Digiart Creation responsive UI polish
[33m4de2899[m[33m ([m[1;31morigin/main[m[33m, [m[1;32mmain[m[33m)[m Digiart Creation branding and theme refresh 3
[33m0c071d2[m Digiart Creation branding and theme refresh 2
[33m94dc9c3[m[33m ([m[1;33mtag: [m[1;33mv1.0-mvp[m[33m)[m Digiart Creation branding and theme refresh
[33m9e8c127[m Initial commit
